export const SIGNUP_LOADING = "REGISTER_LOADING";
export const SIGNUP_SUCCESS = "REGISTER_SUCCESS";
export const SIGNUP_ERROR = "REGISTER_ERROR";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const PROFILES_LOADING = "PROFILES_LOADING";
export const PROFILES_LOAD_SUCCESS = "PROFILES_LOAD_SUCCESS"
export const PROFILES_LOAD_ERROR = "PROFILES_LOAD_ERROR"

export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_LOAD_SUCCESS = "PROFILE_LOAD_SUCCESS"
export const PROFILE_LOAD_ERROR = "PROFILE_LOAD_ERROR"
