export const SIGNUP_LOADING = "REGISTER_LOADING";
export const SIGNUP_SUCCESS = "REGISTER_SUCCESS";
export const SIGNUP_ERROR = "REGISTER_ERROR";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";